### ISSUE TITLE
aws_region is mandatory for AWS cluster but not validated

### ISSUE THREAD

**Issue by mpagot** [sap-linuxlab/community.sles-for-sap#41]
I'm creating a deployment with playbook using `cluster` role from this repo: https://github.com/SUSE/qe-sap-deployment/pull/202

I noticed that, if I forgot to provide `aws_region`, the role fails as the variable is needed by task `Ensure config file has cluster block`. 

That's fine but:
- it is not properly documented in the readme,  in the `Required variables for AWS` section of https://github.com/sap-linuxlab/community.sles-for-sap/blob/00c51824c9d338301705538564bd3a22a7cc1827/roles/cluster/README.md?plain=1#L144
- it is not validated by task `Ensure that AWS specific variables are supplied`

**Comment by marcelmamula** [comment]
PR was merged.
